# Generated by Django 4.1.6 on 2023-02-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='disciplina_associada',
            new_name='cursando_disciplina',
        ),
    ]
