# Generated by Django 4.1.6 on 2023-02-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('professores', '0002_professor_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso'),
        ),
    ]
